[server]
listen_addr = "0.0.0.0:8080"
health_addr = "0.0.0.0:8081"

[adapter]
url = "https://eth-sepolia.g.alchemy.com/v2/iR-o8s0PPaLM7yCqrmna9ANzqvx7mF8B"
router_address = "0xff42b3db9f1040539a3741434e4b33b352fabd80"

[signer]
# Generate a key here by running the binary with `<binary> key generate`
keystore_path = "~/.ibc-attestor/ibc-attestor-keystore"
